steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/p-front-brasil/ws:latest', '.']
images:
- 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/p-front-brasil/ws:latest'
options:
  logging: CLOUD_LOGGING_ONLY
